# Starting from a Python 3.10 base image
FROM python:3.10

# Python and Poetry versions
ARG PYTHON_VERSION=3.10
ARG POETRY_VERSION=1.5.1

# Timezone
ENV TZ=Etc/UTC

# Create a new user 'admin' and set the login shell to /bin/sh
RUN useradd -ms /bin/sh admin

# Set the working directory to /zoish and copy files
WORKDIR /zoish
COPY --chown=admin:admin . /zoish

# Install system dependencies needed for your project (if any)
RUN apt-get update && apt-get install -y --no-install-recommends \
        make \
        build-essential \
        mecab-ipadic-utf8 \
        git \
        gnumeric && \
    DEBIAN_FRONTEND=noninteractive apt-get -y install tzdata && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install and setup poetry
RUN pip3 install --upgrade pip && \
    pip install "poetry==$POETRY_VERSION" && \
    poetry config virtualenvs.create false && \
    poetry cache clear --all pypi && \
    poetry install  --no-interaction --no-ansi

# Switch to the 'admin' user and set permissions
USER admin
RUN chmod +x ./run.sh

# Set the entrypoint for the container
CMD ["bash", "./run.sh"]
